name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image. 
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: mlspec/mlspeclib-action-docker

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          tag_with_sha: true
          tag_with_ref: true
          push: false

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Confirm build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          tag_with_sha: true
          tag_with_ref: true
          push: false

      - name: Log into registry
        run: echo "${{ secrets.GITHUBTOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push to registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          tag_with_sha: true
          tag_with_ref: true
          push: true          
