name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image. 
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: mlspeclib-action-docker

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2


      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          repository: mlspec/mlspeclib-action-docker
          tag_with_sha: true
          tag_with_ref: true
          push: false

      - name: Log into registry
        run: echo "${{ secrets.GITHUBTOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and publish Docker Image to GitHub Packages Registry
        uses: VaultVulp/gp-docker-action@1.1.2
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: ${{ secrets.GITHUBTOKEN }}
          # Docker Image name
          image-name: mlspeclib-action-docker 

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          repository: mlspec/mlspeclib-action-docker
          tag_with_sha: true
          tag_with_ref: true
          push: true          
